export const oebbookInfo = {
    'Ruth': [
        { chapter: 1, verses: 22 },
        { chapter: 2, verses: 23 },
        { chapter: 3, verses: 18 },
        { chapter: 4, verses: 22 },
    ],
    'Esther': [
        { chapter: 1, verses: 22 },
        { chapter: 2, verses: 23 },
        { chapter: 3, verses: 15 },
        { chapter: 4, verses: 17 },
        { chapter: 5, verses: 14 },
        { chapter: 6, verses: 14 },
        { chapter: 7, verses: 10 },
        { chapter: 8, verses: 17 },
        { chapter: 9, verses: 32 },
        { chapter: 10, verses: 3 },
    ],
    'Psalms': [
        { chapter: 1, verses: 6 },
        { chapter: 2, verses: 12 },
        { chapter: 3, verses: 8 },
        { chapter: 4, verses: 8 },
        { chapter: 5, verses: 12 },
        { chapter: 6, verses: 10 },
        { chapter: 7, verses: 17 },
        { chapter: 8, verses: 9 },
        { chapter: 9, verses: 20 },
        { chapter: 10, verses: 18 },
        { chapter: 11, verses: 7 },
        { chapter: 12, verses: 8 },
        { chapter: 13, verses: 6 },
        { chapter: 14, verses: 7 },
        { chapter: 15, verses: 5 },
        { chapter: 16, verses: 11 },
        { chapter: 17, verses: 15 },
        { chapter: 18, verses: 50 },
        { chapter: 19, verses: 14 },
        { chapter: 20, verses: 9 },
        { chapter: 21, verses: 13 },
        { chapter: 22, verses: 31 },
        { chapter: 23, verses: 6 },
        { chapter: 24, verses: 10 },
        { chapter: 25, verses: 22 },
        { chapter: 26, verses: 12 },
        { chapter: 27, verses: 14 },
        { chapter: 28, verses: 9 },
        { chapter: 29, verses: 11 },
        { chapter: 30, verses: 12 },
        { chapter: 31, verses: 24 },
        { chapter: 32, verses: 11 },
        { chapter: 33, verses: 22 },
        { chapter: 34, verses: 22 },
        { chapter: 35, verses: 28 },
        { chapter: 36, verses: 12 },
        { chapter: 37, verses: 40 },
        { chapter: 38, verses: 22 },
        { chapter: 39, verses: 13 },
        { chapter: 40, verses: 17 },
        { chapter: 41, verses: 13 },
        { chapter: 42, verses: 11 },
        { chapter: 43, verses: 5 },
        { chapter: 44, verses: 26 },
        { chapter: 45, verses: 17 },
        { chapter: 46, verses: 11 },
        { chapter: 47, verses: 9 },
        { chapter: 48, verses: 14 },
        { chapter: 49, verses: 20 },
        { chapter: 50, verses: 23 },
        { chapter: 51, verses: 19 },
        { chapter: 52, verses: 9 },
        { chapter: 53, verses: 6 },
        { chapter: 54, verses: 7 },
        { chapter: 55, verses: 23 },
        { chapter: 56, verses: 13 },
        { chapter: 57, verses: 11 },
        { chapter: 58, verses: 11 },
        { chapter: 59, verses: 17 },
        { chapter: 60, verses: 12 },
        { chapter: 61, verses: 8 },
        { chapter: 62, verses: 12 },
        { chapter: 63, verses: 11 },
        { chapter: 64, verses: 10 },
        { chapter: 65, verses: 13 },
        { chapter: 66, verses: 20 },
        { chapter: 67, verses: 7 },
        { chapter: 68, verses: 35 },
        { chapter: 69, verses: 36 },
        { chapter: 70, verses: 5 },
        { chapter: 71, verses: 24 },
        { chapter: 72, verses: 20 },
        { chapter: 73, verses: 28 },
        { chapter: 74, verses: 23 },
        { chapter: 75, verses: 10 },
        { chapter: 76, verses: 12 },
        { chapter: 77, verses: 20 },
        { chapter: 78, verses: 72 },
        { chapter: 79, verses: 13 },
        { chapter: 80, verses: 19 },
        { chapter: 81, verses: 16 },
        { chapter: 82, verses: 8 },
        { chapter: 83, verses: 18 },
        { chapter: 84, verses: 12 },
        { chapter: 85, verses: 13 },
        { chapter: 86, verses: 17 },
        { chapter: 87, verses: 7 },
        { chapter: 88, verses: 18 },
        { chapter: 89, verses: 52 },
        { chapter: 90, verses: 17 },
        { chapter: 91, verses: 16 },
        { chapter: 92, verses: 15 },
        { chapter: 93, verses: 5 },
        { chapter: 94, verses: 23 },
        { chapter: 95, verses: 11 },
        { chapter: 96, verses: 13 },
        { chapter: 97, verses: 12 },
        { chapter: 98, verses: 9 },
        { chapter: 99, verses: 9 },
        { chapter: 100, verses: 5 },
        { chapter: 101, verses: 8 },
        { chapter: 102, verses: 28 },
        { chapter: 103, verses: 22 },
        { chapter: 104, verses: 35 },
        { chapter: 105, verses: 45 },
        { chapter: 106, verses: 48 },
        { chapter: 107, verses: 43 },
        { chapter: 108, verses: 13 },
        { chapter: 109, verses: 31 },
        { chapter: 110, verses: 7 },
        { chapter: 111, verses: 10 },
        { chapter: 112, verses: 10 },
        { chapter: 113, verses: 9 },
        { chapter: 114, verses: 8 },
        { chapter: 115, verses: 18 },
        { chapter: 116, verses: 19 },
        { chapter: 117, verses: 2 },
        { chapter: 118, verses: 29 },
        { chapter: 119, verses: 176 },
        { chapter: 120, verses: 7 },
        { chapter: 121, verses: 8 },
        { chapter: 122, verses: 9 },
        { chapter: 123, verses: 4 },
        { chapter: 124, verses: 8 },
        { chapter: 125, verses: 5 },
        { chapter: 126, verses: 6 },
        { chapter: 127, verses: 5 },
        { chapter: 128, verses: 6 },
        { chapter: 129, verses: 8 },
        { chapter: 130, verses: 8 },
        { chapter: 131, verses: 3 },
        { chapter: 132, verses: 18 },
        { chapter: 133, verses: 3 },
        { chapter: 134, verses: 3 },
        { chapter: 135, verses: 21 },
        { chapter: 136, verses: 26 },
        { chapter: 137, verses: 9 },
        { chapter: 138, verses: 8 },
        { chapter: 139, verses: 24 },
        { chapter: 140, verses: 13 },
        { chapter: 141, verses: 10 },
        { chapter: 142, verses: 7 },
        { chapter: 143, verses: 12 },
        { chapter: 144, verses: 15 },
        { chapter: 145, verses: 21 },
        { chapter: 146, verses: 10 },
        { chapter: 147, verses: 20 },
        { chapter: 148, verses: 14 },
        { chapter: 149, verses: 9 },
        { chapter: 150, verses: 6 },
    ],
    'Hosea': [
        { chapter: 1, verses: 11 },
        { chapter: 2, verses: 23 },
        { chapter: 3, verses: 5 },
        { chapter: 4, verses: 19 },
        { chapter: 5, verses: 15 },
        { chapter: 6, verses: 11 },
        { chapter: 7, verses: 16 },
        { chapter: 8, verses: 14 },
        { chapter: 9, verses: 17 },
        { chapter: 10, verses: 15 },
        { chapter: 11, verses: 12 },
        { chapter: 12, verses: 14 },
        { chapter: 13, verses: 16 },
        { chapter: 14, verses: 9 },
    ],
    'Joel': [
        { chapter: 1, verses: 20 },
        { chapter: 2, verses: 32 },
        { chapter: 3, verses: 21 },
    ],
    'Amos': [
        { chapter: 1, verses: 15 },
        { chapter: 2, verses: 16 },
        { chapter: 3, verses: 15 },
        { chapter: 4, verses: 13 },
        { chapter: 5, verses: 27 },
        { chapter: 6, verses: 14 },
        { chapter: 7, verses: 17 },
        { chapter: 8, verses: 14 },
        { chapter: 9, verses: 15 },
    ],
    'Obadiah': [
        { chapter: 1, verses: 21 },
    ],
    'Jonah': [
        { chapter: 1, verses: 17 },
        { chapter: 2, verses: 10 },
        { chapter: 3, verses: 10 },
        { chapter: 4, verses: 11 },
    ],
    'Micah': [
        { chapter: 1, verses: 16 },
        { chapter: 2, verses: 13 },
        { chapter: 3, verses: 12 },
        { chapter: 4, verses: 13 },
        { chapter: 5, verses: 15 },
        { chapter: 6, verses: 16 },
        { chapter: 7, verses: 20 },
    ],
    'Nahum': [
        { chapter: 1, verses: 15 },
        { chapter: 2, verses: 13 },
        { chapter: 3, verses: 19 },
    ],
    'Habakkuk': [
        { chapter: 1, verses: 17 },
        { chapter: 2, verses: 20 },
        { chapter: 3, verses: 19 },
    ],
    'Zephaniah': [
        { chapter: 1, verses: 18 },
        { chapter: 2, verses: 15 },
        { chapter: 3, verses: 20 },
    ],
    'Haggai': [
        { chapter: 1, verses: 15 },
        { chapter: 2, verses: 23 },
    ],
    'Zechariah': [
        { chapter: 1, verses: 21 },
        { chapter: 2, verses: 13 },
        { chapter: 3, verses: 10 },
        { chapter: 4, verses: 14 },
        { chapter: 5, verses: 14 },
        { chapter: 6, verses: 15 },
        { chapter: 7, verses: 14 },
        { chapter: 8, verses: 23 },
        { chapter: 9, verses: 17 },
        { chapter: 10, verses: 12 },
        { chapter: 11, verses: 17 },
        { chapter: 12, verses: 14 },
        { chapter: 13, verses: 9 },
        { chapter: 14, verses: 21 },
    ],
    'Malachi': [
        { chapter: 1, verses: 14 },
        { chapter: 2, verses: 17 },
        { chapter: 3, verses: 18 },
        { chapter: 4, verses: 6 },
    ],
    'Matthew': [
        { chapter: 1, verses: 25 },
        { chapter: 2, verses: 23 },
        { chapter: 3, verses: 17 },
        { chapter: 4, verses: 25 },
        { chapter: 5, verses: 48 },
        { chapter: 6, verses: 34 },
        { chapter: 7, verses: 29 },
        { chapter: 8, verses: 34 },
        { chapter: 9, verses: 38 },
        { chapter: 10, verses: 42 },
        { chapter: 11, verses: 30 },
        { chapter: 12, verses: 50 },
        { chapter: 13, verses: 58 },
        { chapter: 14, verses: 36 },
        { chapter: 15, verses: 39 },
        { chapter: 16, verses: 28 },
        { chapter: 17, verses: 27 },
        { chapter: 18, verses: 35 },
        { chapter: 19, verses: 30 },
        { chapter: 20, verses: 34 },
        { chapter: 21, verses: 46 },
        { chapter: 22, verses: 46 },
        { chapter: 23, verses: 39 },
        { chapter: 24, verses: 51 },
        { chapter: 25, verses: 46 },
        { chapter: 26, verses: 75 },
        { chapter: 27, verses: 66 },
        { chapter: 28, verses: 20 },
    ],
    'Mark': [
        { chapter: 1, verses: 45 },
        { chapter: 2, verses: 28 },
        { chapter: 3, verses: 35 },
        { chapter: 4, verses: 41 },
        { chapter: 5, verses: 43 },
        { chapter: 6, verses: 56 },
        { chapter: 7, verses: 37 },
        { chapter: 8, verses: 38 },
        { chapter: 9, verses: 50 },
        { chapter: 10, verses: 52 },
        { chapter: 11, verses: 33 },
        { chapter: 12, verses: 44 },
        { chapter: 13, verses: 37 },
        { chapter: 14, verses: 72 },
        { chapter: 15, verses: 47 },
        { chapter: 16, verses: 20 },
    ],
    'Luke': [
        { chapter: 1, verses: 80 },
        { chapter: 2, verses: 52 },
        { chapter: 3, verses: 38 },
        { chapter: 4, verses: 44 },
        { chapter: 5, verses: 39 },
        { chapter: 6, verses: 49 },
        { chapter: 7, verses: 50 },
        { chapter: 8, verses: 56 },
        { chapter: 9, verses: 62 },
        { chapter: 10, verses: 42 },
        { chapter: 11, verses: 54 },
        { chapter: 12, verses: 59 },
        { chapter: 13, verses: 35 },
        { chapter: 14, verses: 35 },
        { chapter: 15, verses: 32 },
        { chapter: 16, verses: 31 },
        { chapter: 17, verses: 37 },
        { chapter: 18, verses: 43 },
        { chapter: 19, verses: 48 },
        { chapter: 20, verses: 47 },
        { chapter: 21, verses: 38 },
        { chapter: 22, verses: 71 },
        { chapter: 23, verses: 56 },
        { chapter: 24, verses: 53 },
    ],
    'John': [
        { chapter: 1, verses: 51 },
        { chapter: 2, verses: 25 },
        { chapter: 3, verses: 36 },
        { chapter: 4, verses: 54 },
        { chapter: 5, verses: 47 },
        { chapter: 6, verses: 71 },
        { chapter: 7, verses: 53 },
        { chapter: 8, verses: 59 },
        { chapter: 9, verses: 41 },
        { chapter: 10, verses: 42 },
        { chapter: 11, verses: 57 },
        { chapter: 12, verses: 50 },
        { chapter: 13, verses: 38 },
        { chapter: 14, verses: 31 },
        { chapter: 15, verses: 27 },
        { chapter: 16, verses: 33 },
        { chapter: 17, verses: 26 },
        { chapter: 18, verses: 40 },
        { chapter: 19, verses: 42 },
        { chapter: 20, verses: 31 },
        { chapter: 21, verses: 25 },
    ],
    'Acts': [
        { chapter: 1, verses: 26 },
        { chapter: 2, verses: 47 },
        { chapter: 3, verses: 26 },
        { chapter: 4, verses: 37 },
        { chapter: 5, verses: 42 },
        { chapter: 6, verses: 15 },
        { chapter: 7, verses: 60 },
        { chapter: 8, verses: 40 },
        { chapter: 9, verses: 43 },
        { chapter: 10, verses: 48 },
        { chapter: 11, verses: 30 },
        { chapter: 12, verses: 25 },
        { chapter: 13, verses: 52 },
        { chapter: 14, verses: 28 },
        { chapter: 15, verses: 41 },
        { chapter: 16, verses: 40 },
        { chapter: 17, verses: 34 },
        { chapter: 18, verses: 28 },
        { chapter: 19, verses: 41 },
        { chapter: 20, verses: 38 },
        { chapter: 21, verses: 40 },
        { chapter: 22, verses: 30 },
        { chapter: 23, verses: 35 },
        { chapter: 24, verses: 27 },
        { chapter: 25, verses: 27 },
        { chapter: 26, verses: 32 },
        { chapter: 27, verses: 44 },
        { chapter: 28, verses: 31 },
    ],
    'Romans': [
        { chapter: 1, verses: 32 },
        { chapter: 2, verses: 29 },
        { chapter: 3, verses: 31 },
        { chapter: 4, verses: 25 },
        { chapter: 5, verses: 21 },
        { chapter: 6, verses: 23 },
        { chapter: 7, verses: 25 },
        { chapter: 8, verses: 39 },
        { chapter: 9, verses: 33 },
        { chapter: 10, verses: 21 },
        { chapter: 11, verses: 36 },
        { chapter: 12, verses: 21 },
        { chapter: 13, verses: 14 },
        { chapter: 14, verses: 23 },
        { chapter: 15, verses: 33 },
        { chapter: 16, verses: 27 },
    ],
    '1 Corinthians': [
        { chapter: 1, verses: 31 },
        { chapter: 2, verses: 16 },
        { chapter: 3, verses: 23 },
        { chapter: 4, verses: 21 },
        { chapter: 5, verses: 13 },
        { chapter: 6, verses: 20 },
        { chapter: 7, verses: 40 },
        { chapter: 8, verses: 13 },
        { chapter: 9, verses: 27 },
        { chapter: 10, verses: 33 },
        { chapter: 11, verses: 34 },
        { chapter: 12, verses: 31 },
        { chapter: 13, verses: 13 },
        { chapter: 14, verses: 40 },
        { chapter: 15, verses: 58 },
        { chapter: 16, verses: 24 },
    ],
    '2 Corinthians': [
        { chapter: 1, verses: 24 },
        { chapter: 2, verses: 17 },
        { chapter: 3, verses: 18 },
        { chapter: 4, verses: 18 },
        { chapter: 5, verses: 21 },
        { chapter: 6, verses: 18 },
        { chapter: 7, verses: 16 },
        { chapter: 8, verses: 24 },
        { chapter: 9, verses: 15 },
        { chapter: 10, verses: 18 },
        { chapter: 11, verses: 33 },
        { chapter: 12, verses: 21 },
        { chapter: 13, verses: 14 },
    ],
    'Galatians': [
        { chapter: 1, verses: 24 },
        { chapter: 2, verses: 21 },
        { chapter: 3, verses: 29 },
        { chapter: 4, verses: 31 },
        { chapter: 5, verses: 26 },
        { chapter: 6, verses: 18 },
    ],
    'Ephesians': [
        { chapter: 1, verses: 23 },
        { chapter: 2, verses: 22 },
        { chapter: 3, verses: 21 },
        { chapter: 4, verses: 32 },
        { chapter: 5, verses: 33 },
        { chapter: 6, verses: 24 },
    ],
    'Philippians': [
        { chapter: 1, verses: 30 },
        { chapter: 2, verses: 30 },
        { chapter: 3, verses: 21 },
        { chapter: 4, verses: 23 },
    ],
    'Colossians': [
        { chapter: 1, verses: 29 },
        { chapter: 2, verses: 23 },
        { chapter: 3, verses: 25 },
        { chapter: 4, verses: 18 },
    ],
    '1 Thessalonians': [
        { chapter: 1, verses: 10 },
        { chapter: 2, verses: 20 },
        { chapter: 3, verses: 13 },
        { chapter: 4, verses: 18 },
        { chapter: 5, verses: 28 },
    ],
    '2 Thessalonians': [
        { chapter: 1, verses: 12 },
        { chapter: 2, verses: 17 },
        { chapter: 3, verses: 18 },
    ],
    '1 Timothy': [
        { chapter: 1, verses: 20 },
        { chapter: 2, verses: 15 },
        { chapter: 3, verses: 16 },
        { chapter: 4, verses: 16 },
        { chapter: 5, verses: 25 },
        { chapter: 6, verses: 21 },
    ],
    '2 Timothy': [
        { chapter: 1, verses: 18 },
        { chapter: 2, verses: 26 },
        { chapter: 3, verses: 17 },
        { chapter: 4, verses: 22 },
    ],
    'Titus': [
        { chapter: 1, verses: 16 },
        { chapter: 2, verses: 15 },
        { chapter: 3, verses: 15 },
    ],
    'Philemon': [
        { chapter: 1, verses: 25 },
    ],
    'Hebrews': [
        { chapter: 1, verses: 14 },
        { chapter: 2, verses: 18 },
        { chapter: 3, verses: 19 },
        { chapter: 4, verses: 16 },
        { chapter: 5, verses: 14 },
        { chapter: 6, verses: 20 },
        { chapter: 7, verses: 28 },
        { chapter: 8, verses: 13 },
        { chapter: 9, verses: 28 },
        { chapter: 10, verses: 39 },
        { chapter: 11, verses: 40 },
        { chapter: 12, verses: 29 },
        { chapter: 13, verses: 25 },
    ],
    'James': [
        { chapter: 1, verses: 27 },
        { chapter: 2, verses: 26 },
        { chapter: 3, verses: 18 },
        { chapter: 4, verses: 17 },
        { chapter: 5, verses: 20 },
    ],
    '1 Peter': [
        { chapter: 1, verses: 25 },
        { chapter: 2, verses: 25 },
        { chapter: 3, verses: 22 },
        { chapter: 4, verses: 19 },
        { chapter: 5, verses: 14 },
    ],
    '2 Peter': [
        { chapter: 1, verses: 21 },
        { chapter: 2, verses: 22 },
        { chapter: 3, verses: 18 },
    ],
    '1 John': [
        { chapter: 1, verses: 10 },
        { chapter: 2, verses: 29 },
        { chapter: 3, verses: 24 },
        { chapter: 4, verses: 21 },
        { chapter: 5, verses: 21 }
    ],
    '2 John': [
        { chapter: 1, verses: 13 },
    ],
    '3 John': [
        { chapter: 1, verses: 15 },
    ],
    'Jude': [
        { chapter: 1, verses: 25 },
    ],
    'Revelation': [
        { chapter: 1, verses: 20 },
        { chapter: 2, verses: 29 },
        { chapter: 3, verses: 22 },
        { chapter: 4, verses: 11 },
        { chapter: 5, verses: 14 },
        { chapter: 6, verses: 17 },
        { chapter: 7, verses: 17 },
        { chapter: 8, verses: 13 },
        { chapter: 9, verses: 21 },
        { chapter: 10, verses: 11 },
        { chapter: 11, verses: 19 },
        { chapter: 12, verses: 17 },
        { chapter: 13, verses: 18 },
        { chapter: 14, verses: 20 },
        { chapter: 15, verses: 8 },
        { chapter: 16, verses: 21 },
        { chapter: 17, verses: 18 },
        { chapter: 18, verses: 24 },
        { chapter: 19, verses: 21 },
        { chapter: 20, verses: 15 },
        { chapter: 21, verses: 27 },
        { chapter: 22, verses: 21 }
    ],
};
